# Describes the format for available automation services
turn_on:
  description: Enable an automation
  target:

turn_off:
  description: Disable an automation
  target:
  fields:
    stop_actions:
      name: Stop actions
      description: Stop currently running actions.
      default: true
      example: true
      selector:
        boolean:

toggle:
  description: Toggle (enable / disable) an automation
  target:

trigger:
  description: Trigger the actions of an automation
  target:
  fields:
    skip_condition:
      name: Skip conditions
      description: Whether or not the conditions will be skipped.
      default: true
      example: true
      selector:
        boolean:

reload:
  description: Reload the automation configuration
